### PR TITLE
DM-6391 afw display needs to be able to display a catalog

### PR DESCRIPTION
**Pull request by stargaser**
Implement _overlayCatalog method.

Use ds9's catalog import tsv to upload a sourceCatalog
and overlay it on the displayed image.

### CODE REVIEW

**Comment by RobertLuptonTheGood** [comment]
How does this work with a remote ds9 display (i.e. tunnelling using ssh)?  This must be a concern for the firefly backend too.

If it doesn't work, this week needs to be rethought.

**Comment by stargaser** [comment]
@RobertLuptonTheGood I overlooked that case. I got ds9 tunneling set up based on the [instructions on c.l.o](https://community.lsst.org/t/using-an-lsst-dev-stack-w-local-ipython-ds9-tutorial/592) and the catalog overlay doesn't work as currently implemented. It works for the firefly backend since there is a websocket connected to whatever server is being used.

**Comment by RobertLuptonTheGood** [comment]
So you write the csv/tsv directly to the webSocket?

In general, I wouldn't assume that you can add smarts to devices, which is why I think that this sort of things belongs in a utility library rather than in interface.py.  However, I think that changing the {{dot}} API to accept lists/vectors would be totally reasonable (even if we might have to loop over them in the ds9 driver -- but I think we wouldn't).  Also, this would work for e.g. {{display_ginga}} which I have not yet pushed --- next time you expand the afwDisplay interface there may well be more devices that you'll have to update.

**Comment by parejkoj** [comment]
Closing this PR to open a new one with my completely different branch: I wasn't even aware that this existed.

**Pull request closed without merging**
